apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: m00nnnn/myfirstrepository:springboot-v23
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/peopledb
        imagePullPolicy: Always
        ports:
        - containerPort: 8087